# Generated by Django 3.2 on 2021-04-24 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feed',
            table='feeds',
        ),
    ]
