version: "3.9"
   
services:
  nginx:
    build: nginx/
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - static_volume:/staticfiles
  web:
    build: blogsearch/
    volumes:
      - ./blogsearch:/app
      - static_volume:/app/staticfiles
    expose:
      - 8000
    depends_on:
      - db
    command: ['bash', 'startup.sh']
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=main

volumes:
  postgres_data:
  static_volume: