# Generated by Django 3.2 on 2022-08-23 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0007_post_hidden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
