# Generated by Django 3.2 on 2022-08-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0008_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
