# Generated by Django 3.2 on 2022-08-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0009_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
