# Generated by Django 3.2 on 2022-08-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0010_post_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
